{{- if .Values.contractDeployer.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "anvil-testnet.fullname" . }}
  labels:
    {{- include "anvil-testnet.labels" . | nindent 4 }}
{{- end }}
