{{- if and .Values.ingress.enabled .Values.tls.generateSelfSigned (not .Values.tls.existingSecret) }}
{{- $fullName := include "anvil-testnet.fullname" . -}}
{{- $hosts := list -}}
{{- range .Values.ingress.tls }}
{{- range .hosts }}
{{- $hosts = append $hosts . }}
{{- end }}
{{- end }}
{{- $ca := genCA "anvil-ca" 365 -}}
{{- $cert := genSignedCert (first $hosts) nil $hosts 365 $ca -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ (first .Values.ingress.tls).secretName }}
  labels:
    {{- include "anvil-testnet.labels" . | nindent 4 }}
type: kubernetes.io/tls
data:
  tls.crt: {{ $cert.Cert | b64enc }}
  tls.key: {{ $cert.Key | b64enc }}
  ca.crt: {{ $ca.Cert | b64enc }}
{{- end }}
