{{- if .Values.secrets.privateKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.name }}
  labels:
    {{- include "contract-deployer.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.secrets.privateKeyKey }}: {{ .Values.secrets.privateKey | quote }}
{{- end }}
