{{- if or (eq .Values.mode "deployment") (eq .Values.mode "job") }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "contract-deployer.fullname" . }}
  labels:
    {{- include "contract-deployer.labels" . | nindent 4 }}
{{- end }}
