{{- if and (eq .Values.mode "deployment") .Values.api.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "contract-deployer.fullname" . }}
  labels:
    {{- include "contract-deployer.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type | default "ClusterIP" }}
  ports:
    - port: {{ .Values.api.port | default 3001 }}
      targetPort: api
      protocol: TCP
      name: api
  selector:
    {{- include "contract-deployer.selectorLabels" . | nindent 4 }}
{{- end }}
