development:
  adapter: redis
  url: <%= Rails.application.config.x.redis.cable_url %>
  channel_prefix: puzzlex_development

test:
  adapter: redis
  url: <%= Rails.application.config.x.redis.cable_url %>
  channel_prefix: puzzlex_test

production:
  adapter: redis
  url: <%= Rails.application.config.x.redis.cable_url %>
  channel_prefix: puzzlex_production
